### ISSUE TITLE
Add (actual) license

### ISSUE THREAD

**Issue by xiongchiamiov** [exavolt/onde#10]
The readme for this project states that it is released into the public domain.  Unfortunately, what this means varies from country to country, and it is generally agreed that in Germany this isn't even possible!  (See [StackOverflow](http://stackoverflow.com/a/219826/120999) and [Wikipedia](http://en.wikipedia.org/wiki/Wikipedia:Granting_work_into_the_public_domain) for more information.)

There are a few licenses created to solve this problem.  [The WTFPL](http://sam.zoy.org/wtfpl/) is a personal favorite, although some may prefer [the Fair license](http://www.opensource.org/licenses/Fair) for its lack of profanity.  There is also the Creative-Commons-created [CC0](http://creativecommons.org/publicdomain/zero/1.0/), if that's more your taste.

**Comment by exavolt** [comment]
Thanks for the feedback about the licensing.

Although there's no actual license file, the project was released in the spirit of [unlicense](http://webcache.googleusercontent.com/search?q=cache:http://unlicense.org/) (it looks like the original site is not accessible; [alt](https://github.com/bendiken/unlicense.org) ). I haven't done more research about whether, on some countries, it's to be considered as an _actual_ license or not.

**Comment by exavolt** [comment]
Changed to WTFPL.

**Comment by artob** [comment]
@exavolt Correct regarding CC0 and the Unlicense being, as a fallback strategy, considered actual licenses in any jurisdictions that otherwise might have trouble recognizing the right of authors to voluntarily waive any and all copyright privileges. Find particulars in [Licensed, License-Free, and Unlicensed Code](http://ar.to/2010/12/licensing-and-unlicensing) and [Dissecting the Unlicense: Software Freedom in Four Clauses and a Link](http://ar.to/2010/01/dissecting-the-unlicense). I'm not sure what the problem with the Unlicense.org website was back when this issue was open, but the website is certainly online now.
